import re

fixes = [
    # cao endings
    ('localizacao','localização'),('Localizacao','Localização'),
    ('gestao','gestão'),('Gestao','Gestão'),
    ('avaliacao','avaliação'),('Avaliacao','Avaliação'),
    ('pontuacao','pontuação'),('Pontuacao','Pontuação'),
    ('manutencao','manutenção'),('Manutencao','Manutenção'),
    ('certificacao','certificação'),('Certificacao','Certificação'),
    ('climatizacao','climatização'),('Climatizacao','Climatização'),
    ('refrigeracao','refrigeração'),('Refrigeracao','Refrigeração'),
    ('iluminacao','iluminação'),('Iluminacao','Iluminação'),
    ('operacao','operação'),('Operacao','Operação'),
    ('elaboracao','elaboração'),('Elaboracao','Elaboração'),
    ('substituicao','substituição'),('Substituicao','Substituição'),
    ('comunicacao','comunicação'),('Comunicacao','Comunicação'),
    ('medicao','medição'),('Medicao','Medição'),
    ('separacao','separação'),('Separacao','Separação'),
    ('poluicao','poluição'),('Poluicao','Poluição'),
    ('combustao','combustão'),('Combustao','Combustão'),
    ('verificacao','verificação'),('Verificacao','Verificação'),
    ('identificacao','identificação'),('Identificacao','Identificação'),
    ('contaminacao','contaminação'),('Contaminacao','Contaminação'),
    ('emissao','emissão'),('Emissao','Emissão'),
    ('geracao','geração'),('Geracao','Geração'),
    ('reducao','redução'),('Reducao','Redução'),
    ('producao','produção'),('Producao','Produção'),
    ('utilizacao','utilização'),('Utilizacao','Utilização'),
    ('funcao','função'),('Funcao','Função'),
    ('instrucao','instrução'),('Instrucao','Instrução'),
    ('integracao','integração'),('Integracao','Integração'),
    ('ocupacao','ocupação'),('Ocupacao','Ocupação'),
    ('solucao','solução'),('Solucao','Solução'),
    ('selecao','seleção'),('Selecao','Seleção'),
    ('adequacao','adequação'),('Adequacao','Adequação'),
    ('vazao','vazão'),('Vazao','Vazão'),
    ('rejeicao','rejeição'),('Rejeicao','Rejeição'),
    ('excecao','exceção'),('Excecao','Exceção'),
    ('aquisicao','aquisição'),('Aquisicao','Aquisição'),
    ('orcamento','orçamento'),('Orcamento','Orçamento'),
    ('posicao','posição'),('Posicao','Posição'),
    ('introducao','introdução'),('Introducao','Introdução'),
    ('correcao','correção'),('Correcao','Correção'),
    ('proporcao','proporção'),('Proporcao','Proporção'),
    ('colecao','coleção'),('Colecao','Coleção'),
    ('negociacao','negociação'),('Negociacao','Negociação'),
    ('demonstracao','demonstração'),('Demonstracao','Demonstração'),
    ('atencao','atenção'),('Atencao','Atenção'),
    ('instalacao','instalação'),('Instalacao','Instalação'),
    ('regulacao','regulação'),('Regulacao','Regulação'),
    ('previsao','previsão'),('Previsao','Previsão'),
    ('transmissao','transmissão'),('Transmissao','Transmissão'),
    ('inspecao','inspeção'),('Inspecao','Inspeção'),
    ('remocao','remoção'),('Remocao','Remoção'),
    ('composicao','composição'),('Composicao','Composição'),
    ('composicoes','composições'),
    ('instalacoes','instalações'),
    ('inspecoes','inspeções'),
    ('avaliacoes','avaliações'),
    ('operacoes','operações'),
    ('medicoes','medições'),('Medicoes','Medições'),
    # oes endings
    ('emissoes','emissões'),('Emissoes','Emissões'),
    ('residuos','resíduos'),('Residuos','Resíduos'),
    ('acoes','ações'),('Acoes','Ações'),
    ('instrucoes','instruções'),('Instrucoes','Instruções'),
    ('condicoes','condições'),('Condicoes','Condições'),
    ('opcoes','opções'),('Opcoes','Opções'),
    ('solucoes','soluções'),('Solucoes','Soluções'),
    ('padroes','padrões'),('Padroes','Padrões'),
    ('exigencias','exigências'),('Exigencias','Exigências'),
    ('excecoes','exceções'),('Excecoes','Exceções'),
    ('reducoes','reduções'),('Reducoes','Reduções'),
    ('tendencias','tendências'),('Tendencias','Tendências'),
    ('evidencias','evidências'),('Evidencias','Evidências'),
    ('espacos','espaços'),('Espacos','Espaços'),
    ('espaco','espaço'),('Espaco','Espaço'),
    ('estacoes','estações'),
    ('solucoes','soluções'),
    ('perigos','perigos'),
    # accented adjectives and nouns
    ('eficiencia','eficiência'),('Eficiencia','Eficiência'),
    ('eficiencias','eficiências'),
    ('experiencia','experiência'),('Experiencia','Experiência'),
    ('frequencia','frequência'),('Frequencia','Frequência'),
    ('exigencia','exigência'),('Exigencia','Exigência'),
    ('sequencia','sequência'),('Sequencia','Sequência'),
    ('estrategia','estratégia'),('Estrategia','Estratégia'),
    ('tecnico','técnico'),('Tecnico','Técnico'),
    ('tecnicos','técnicos'),
    ('tecnica','técnica'),('Tecnica','Técnica'),
    ('tecnicas','técnicas'),
    ('nivel','nível'),('Nivel','Nível'),
    ('niveis','níveis'),('Niveis','Níveis'),
    ('praticas','práticas'),('Praticas','Práticas'),
    ('pratica','prática'),('Pratica','Prática'),
    ('minima','mínima'),('Minima','Mínima'),
    ('minimo','mínimo'),('Minimo','Mínimo'),
    ('maxima','máxima'),('Maxima','Máxima'),
    ('maximo','máximo'),('Maximo','Máximo'),
    ('propria','própria'),('Propria','Própria'),
    ('proprio','próprio'),('Proprio','Próprio'),
    ('proprias','próprias'),('proprios','próprios'),
    ('basica','básica'),('Basica','Básica'),
    ('basico','básico'),('Basico','Básico'),
    ('basicas','básicas'),('basicos','básicos'),
    ('critica','crítica'),('Critica','Crítica'),
    ('critico','crítico'),('Critico','Crítico'),
    ('criticos','críticos'),
    ('politica','política'),('Politica','Política'),
    ('politicas','políticas'),('Politicas','Políticas'),
    ('energetico','energético'),('Energetico','Energético'),
    ('energetica','energética'),('Energetica','Energética'),
    ('energeticos','energéticos'),
    ('hidrico','hídrico'),('Hidrico','Hídrico'),
    ('hidrica','hídrica'),('Hidrica','Hídrica'),
    ('potavel','potável'),('Potavel','Potável'),
    ('solidos','sólidos'),('Solidos','Sólidos'),
    ('solido','sólido'),
    ('organicos','orgânicos'),('organico','orgânico'),('Organico','Orgânico'),
    ('climatico','climático'),('Climatico','Climático'),
    ('climaticos','climáticos'),
    ('plastico','plástico'),('Plastico','Plástico'),
    ('plasticos','plásticos'),
    ('automatico','automático'),('Automatico','Automático'),
    ('eletrico','elétrico'),('Eletrico','Elétrico'),
    ('eletricos','elétricos'),('eletrica','elétrica'),('Eletrica','Elétrica'),
    ('eletronico','eletrônico'),('Eletronico','Eletrônico'),
    ('eletronicos','eletrônicos'),('Eletronicos','Eletrônicos'),
    ('quimica','química'),('Quimica','Química'),
    ('quimico','químico'),('Quimico','Químico'),
    ('quimicos','químicos'),
    ('indice','índice'),('Indice','Índice'),
    ('calculo','cálculo'),('Calculo','Cálculo'),
    ('calculos','cálculos'),
    ('especifico','específico'),('Especifico','Específico'),
    ('especifica','específica'),('Especifica','Específica'),
    ('especificos','específicos'),('especificas','específicas'),
    ('agua','água'),('Agua','Água'),
    ('aguas','águas'),('Aguas','Águas'),
    ('lampadas','lâmpadas'),('Lampadas','Lâmpadas'),
    ('lampada','lâmpada'),('Lampada','Lâmpada'),
    ('topicos','tópicos'),('Topicos','Tópicos'),
    ('topico','tópico'),('Topico','Tópico'),
    ('publico','público'),('Publico','Público'),
    ('publicos','públicos'),('publica','pública'),('Publica','Pública'),
    ('atraves','através'),('Atraves','Através'),
    ('apos','após'),('Apos','Após'),
    ('ultimos','últimos'),('Ultimos','Últimos'),
    ('ultimas','últimas'),('ultimo','último'),('Ultimo','Último'),
    ('unico','único'),('Unico','Único'),
    ('unicos','únicos'),('unica','única'),('Unica','Única'),
    ('onibus','ônibus'),('Onibus','Ônibus'),
    ('papelao','papelão'),('Papelao','Papelão'),
    ('tonner','toner'),
    ('orgao','órgão'),('Orgao','Órgão'),
    ('periodica','periódica'),('periodico','periódico'),('periodicos','periódicos'),
    ('logistica','logística'),('Logistica','Logística'),
    ('caracteristicas','características'),('Caracteristicas','Características'),
    ('padrao','padrão'),('Padrao','Padrão'),
    ('estao','estão'),('Estao','Estão'),
    ('domestico','doméstico'),('Domestico','Doméstico'),
    ('domesticos','domésticos'),
    ('economica','econômica'),('Economica','Econômica'),
    ('economico','econômico'),('Economico','Econômico'),
    ('economicos','econômicos'),
    ('historico','histórico'),('Historico','Histórico'),
    ('sistematico','sistemático'),('Sistematico','Sistemático'),
    ('sistematica','sistemática'),
    ('automatizada','automatizada'),
    ('resiliencia','resiliência'),('Resiliencia','Resiliência'),
    ('biologico','biológico'),('Biologico','Biológico'),
    ('biologicos','biológicos'),
    ('fisico','físico'),('Fisico','Físico'),
    ('fisicos','físicos'),('fisica','física'),('Fisica','Física'),
    ('mecanico','mecânico'),('Mecanico','Mecânico'),
    ('mecanicos','mecânicos'),('mecanica','mecânica'),
    ('toxico','tóxico'),('Toxicos','Tóxicos'),
    ('atmosfera','atmosfera'),
    ('ozonio','ozônio'),('Ozonio','Ozônio'),
    ('aereo','aéreo'),('Aereo','Aéreo'),
    ('umido','úmido'),('Umido','Úmido'),
    ('umidade','umidade'),
    ('acustica','acústica'),('Acustica','Acústica'),
    ('optica','óptica'),('Optica','Óptica'),
    ('quimicas','químicas'),
    ('saude','saúde'),('Saude','Saúde'),
    ('contribuicao','contribuição'),('Contribuicao','Contribuição'),
    ('mitigacao','mitigação'),('Mitigacao','Mitigação'),
    ('adaptacao','adaptação'),('Adaptacao','Adaptação'),
    ('absorcao','absorção'),('Absorcao','Absorção'),
    ('captacao','captação'),('Captacao','Captação'),
    ('sinalizacao','sinalização'),('Sinalizacao','Sinalização'),
    ('fiscalizacao','fiscalização'),('Fiscalizacao','Fiscalização'),
    ('aprovacao','aprovação'),('Aprovacao','Aprovação'),
    ('elaborado','elaborado'),
    ('implantacao','implantação'),('Implantacao','Implantação'),
    ('gerenciamento','gerenciamento'),
    ('monitoramento','monitoramento'),
    ('rastreamento','rastreamento'),
    ('rastreabilidade','rastreabilidade'),
    ('descarte','descarte'),
    ('armazenagem','armazenagem'),
    ('restricoes','restrições'),('Restricoes','Restrições'),
    ('restricao','restrição'),('Restricao','Restrição'),
    ('retificacao','retificação'),
    ('compatibilizacao','compatibilização'),
    ('fiscalizacao','fiscalização'),
    ('proibicao','proibição'),('Proibicao','Proibição'),
    ('aplicacao','aplicação'),('Aplicacao','Aplicação'),
    ('associacao','associação'),('Associacao','Associação'),
    ('declaracao','declaração'),('Declaracao','Declaração'),
    ('embalagem','embalagem'),
    ('residuo','resíduo'),('Residuo','Resíduo'),
]

def apply_fixes(content):
    for old, new in fixes:
        content = content.replace(old, new)
    # word-boundary replacements for tricky ones
    content = re.sub(r'\bnao\b', 'não', content)
    content = re.sub(r'\bNao\b', 'Não', content)
    content = re.sub(r'\bsao\b', 'são', content)
    content = re.sub(r'\bSao\b', 'São', content)
    content = re.sub(r'\bate\b', 'até', content)
    content = re.sub(r'\bAte\b', 'Até', content)
    content = re.sub(r'\bja\b', 'já', content)
    content = re.sub(r'\bJa\b', 'Já', content)
    content = re.sub(r'\bha\b', 'há', content)
    content = re.sub(r'\bHa\b', 'Há', content)
    content = re.sub(r'\bsera\b', 'será', content)
    content = re.sub(r'\bSera\b', 'Será', content)
    content = re.sub(r'\besta\b', 'está', content)
    content = re.sub(r'\bEsta\b', 'Está', content)
    return content

for fname in ['src/data/prerequisites-v41.js', 'src/data/prerequisites-v5.js']:
    with open(fname, 'r', encoding='utf-8') as f:
        content = f.read()
    fixed = apply_fixes(content)
    with open(fname, 'w', encoding='utf-8') as f:
        f.write(fixed)
    print(f'Fixed: {fname}')

print('All done.')
